# serial config
com-port = "COM4"
baud-rate = 9600

# model config
model-path = "./640px_100epoch.pt"

# video config
video-source = 1
video-width = 640
video-height = 480

# tolerances config
min-confidence = 0.8
person-class-id = 0
min-target-size-x = 60
min-target-size-y = 200
hitbox-offset-x-fraction = 0.0
hitbox-offset-y-fraction = -0.5

# misc config
hitbox-size-fraction = 0.1
trigger-cooldown-seconds = 3
